postgresInit:
	docker run --name postgres15 -p 5433:5432 -e POSTGRES_USER=root -e POSTGRES_PASSWORD=password -d postgres:15-alpine

postgres:
	docker exec -it postgres15 psql

createDb:
	docker exec -it postgres15 createdb --username=root --owner=root text-hive-db

dropDb:
	docker exec -it postgres15 dropdb text-hive-db

.PHONY: postgresInit postgres createDb